---
- hosts: all
  become: yes
  tasks:
    - name: apt update
      apt:
        update-cache: yes

    - name: Checking docker on latest version
      apt: name=docker.io state=latest

    - name: Checking python
      apt: name=python state=latest

    - name: Checking docker-compose on latest version
      apt: name=docker-compose state=latest

    - name: Create "docker" group
      group:
        name: docker
        state: present

    - name: Add remote vagrant user to "docker" group
      user:
        name: vagrant
        group: docker
        state: present

    - name: Copy website files to the server's document root
      copy:
        src: docker-node/
        dest: project/
        mode: preserve

    - name: Deploy Docker Compose
      docker_compose:
        project_src: project/
        state: present
